# Site settings
title: Phoenix Spokes People
email: bike@phoenixspokespeople.org
description: Inspiring cycling as a transportation option for the city of Phoenix.
url:  http://phoenixspokespeople.org/
twitter_username: phxspokespeople

# Build settings
markdown: kramdown
hightlighter: pygments

# Pagination
paginate: 15

collections:
  resources:
    output: true
    permalink: /resources/:path/


